INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '1', '101', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '1', '102', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '2', '201', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '4', '401', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` (`porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '5', '501', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '7', '701', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '8', '801', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '8', '802', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '9', '901', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '9', '902', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');

INSERT INTO `bdevaluacion_2020`.`semaforo` ( `porc_calidad`, `porc_deb_proc`, `porc_descuento`, `id_contrato`, `id_prestador`, `id_modalidad`, `id_componente`, `id_tema`, `id_ano`, `id_mes`, `incumplimiento_grave`, `nt1`, `nt2`, `nt3`, `gi1`, `gi2`, `gi3`, `gi4`, `gi5`, `gi6`, `gi7`, `descripcion_incumplimiento_grave`, `logros_prestador`, `dificultades_prestador`, `debido_proceso`, `asistencia_tecnica`, `otras_observaciones`, `id_interventor`, `estado`) VALUES ( 0, 0, 0, '4600084195', '9', '11', '9', '903', '2020', '4', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Pendiente por visitar', 'Admin', '1');
